package com.radiance.mixins.vulkan_render_integration;

import com.mojang.blaze3d.opengl.GlShaderModule;
import com.mojang.blaze3d.shaders.ShaderSource;
import com.mojang.blaze3d.shaders.ShaderType;
import com.radiance.mixin_related.extensions.vulkan_render_integration.ICompiledShaderExt;
import net.minecraft.client.renderer.ShaderDefines;
import net.minecraft.resources.Identifier;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

/**
 * 26.2 shader source-capture. The mod's native backend needs the GLSL source of every shader MC
 * compiles, and records it via {@link ICompiledShaderExt} for {@code ShaderProgramMixins} to forward.
 *
 * <p>1.21.11 ran MC with no GL context, so it skipped the real GL compile entirely and returned a
 * virtual {@link GlShaderModule} carrying only the source. That does not work under the 26.2 port:
 * MC runs on its own <em>real</em> GL backend (so the GL-command capture works), and its
 * {@code ShaderManager} actually links the programs and treats a link failure as fatal ("Failed to
 * load required shader programs"). A virtual, fake-id module makes {@code glLinkProgram} fail with
 * "handle does not refer to an object generated by OpenGL".
 *
 * <p>So let MC compile the real shader and merely record the resolved source on the returned module
 * at RETURN. The native backend still translates that source; MC's own (never-presented) GL programs
 * link successfully so resource loading completes.
 */
// GlDevice is package-private, so target it by name rather than by .class.
@Mixin(targets = "com.mojang.blaze3d.opengl.GlDevice")
public class GlDeviceMixins {

    @Inject(method = "getOrCompileShader", at = @At("RETURN"))
    private void captureShaderSource(Identifier id, ShaderType type, ShaderDefines defines,
        ShaderSource shaderSource, CallbackInfoReturnable<GlShaderModule> cir) {
        GlShaderModule module = cir.getReturnValue();
        if (module == null || module == GlShaderModule.INVALID_SHADER) {
            return;
        }
        String source = shaderSource.get(id, type);
        if (source != null) {
            ((ICompiledShaderExt) (Object) module).radiance$setResolvedSource(source);
        }
    }
}
